# using version 2 of docker compose
version: "2"

# compose completes two services, one for the server and one for the database
services:
  practice-docker:
    image: bilalmalik4321/practice_docker
    ports:
      - 80:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'  # wait till file exists, before running the server
    depends_on: 
      - db
    environment: 
      - DATABASE_URL=postgres://postgres:password@db:5432/practicedocker
      - PORT=3000
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=practicedocker
