# Automatically generate a release when pushes are put in master
# name of tag/release is also the value in the secret variable version in repo
name: "tagged release"

on:
  pull_request:
    branches:
      - master

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: echo label
        run: echo "${{ toJson(github.event.pull_request.labels[0].name) }}"

      - name: clone repo
        run: | 
          git clone https://github.com/bilalmalik4321/practice_docker.git
          cd practice_docker

      - name: list tags
        run: git tag

      - name: set-variable-env
        # run: bash scripts/pipeline/autoincrement.sh
        run: bash scripts/pipeline/autoincrement.sh ${{ toJson(github.event.pull_request.labels[0].name) }}

      - name: echo env version
        run: echo ${{env.VERSION}}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{env.VERSION}}"
          prerelease: false
          title: "Development Build"
