# Automatically generate a release when pushes are put in master
# name of tag/release is also the value in the secret variable version in repo
name: "tagged release"

on:
  push:
    branches:
      - "master"

env:
  version_number: "v0.0.1"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      # ...

      - name: set-variable-env
        run: bash .github/workflows/autoincrement.sh

      - name: set output
        id: set
        run: |

          chmod +x autoincrement.sh
          ./autoincrement.sh

      - name: use output
        run: |
          echo $VERSION
          echo ${{env.VERSION }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{env.version_number}}"
          prerelease: false
          title: "Development Build"
